In [ ]:
import csv

def calculate_rating_statistics(ratings):
    ratings = [float(r) for r in ratings if r]
    if not ratings:
        return None, None
    avg_rating = sum(ratings) / len(ratings)
    min_rating = min(ratings)
    max_rating = max(ratings)
    return avg_rating, min_rating, max_rating

with open("movies.csv","r")as f:
    contents = list(csv.reader(f))
    header = contents[0]
    data = contents[1:]
    print(header)
    print(data[:5])

['Movie Name', 'Industry', 'Rating', 'Turnover (INR)']
[['Avengers: Endgame', 'Hollywood', '4.8', '16650000000'], ['Bajrangi Bhaijaan', 'Bollywood', '8.8', '15220000000'], ['Inception', 'Hollywood', '9.5', '17630000000'], ['War', 'Bollywood', '8.9', '900000000'], ['Titanic', 'Hollywood', '7.8', '6950000000']]

In [16]:
import pandas as pd
df = pd.read_csv("movies.csv")
print(df.head())
print("top 10 rows")
print(df.head(10))
print("bottom 10 rows")
print(df.tail(10))

          Movie Name   Industry  Rating  Turnover (INR)
0  Avengers: Endgame  Hollywood     4.8     16650000000
1  Bajrangi Bhaijaan  Bollywood     8.8     15220000000
2          Inception  Hollywood     9.5     17630000000
3                War  Bollywood     8.9       900000000
4            Titanic  Hollywood     7.8      6950000000
top 10 rows
          Movie Name   Industry  Rating  Turnover (INR)
0  Avengers: Endgame  Hollywood     4.8     16650000000
1  Bajrangi Bhaijaan  Bollywood     8.8     15220000000
2          Inception  Hollywood     9.5     17630000000
3                War  Bollywood     8.9       900000000
4            Titanic  Hollywood     7.8      6950000000
5             Dangal  Bollywood     9.2     19940000000
6                War  Bollywood     5.5     16950000000
7                KGF      Local     3.9       370000000
8  Avengers: Endgame  Hollywood     7.2      4790000000
9           Drishyam      Local     9.4     18220000000
bottom 10 rows
           Movie Name   Industry  Rating  Turnover (INR)
90           3 Idiots  Bollywood     4.4      6090000000
91  Bajrangi Bhaijaan  Bollywood     8.3     17320000000
92           3 Idiots  Bollywood     5.9     18400000000
93          Inception  Hollywood     9.0      5660000000
94             Avatar  Hollywood     8.6     11980000000
95              Lucia      Local     4.9       290000000
96             Asuran      Local     9.8     16220000000
97  Avengers: Endgame  Hollywood     9.4      2650000000
98    Chennai Express  Bollywood     8.2      4770000000
99    The Dark Knight  Hollywood     7.9      2450000000

In [17]:
df.shape

(100, 4)

In [18]:
df[2:6]

  Movie Name   Industry  Rating  Turnover (INR)
2  Inception  Hollywood     9.5     17630000000
3        War  Bollywood     8.9       900000000
4    Titanic  Hollywood     7.8      6950000000
5     Dangal  Bollywood     9.2     19940000000

In [20]:
df.Rating

0     4.8
1     8.8
2     9.5
3     8.9
4     7.8
     ...
95    4.9
96    9.8
97    9.4
98    8.2
99    7.9
Name: Rating, Length: 100, dtype: float64

In [ ]:
df["Rating"]

0     4.8
1     8.8
2     9.5
3     8.9
4     7.8
     ...
95    4.9
96    9.8
97    9.4
98    8.2
99    7.9
Name: Rating, Length: 100, dtype: float64

In [22]:
type(df["Rating"])

pandas.core.series.Series

In [23]:
type(df)

pandas.core.frame.DataFrame

In [26]:
dir(df.Rating)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [28]:
print(df.Rating.min())
print(df.Rating.max())
print(df.Rating.mean())
print(df.Rating.median())

3.0
9.9
6.621
6.8

In [34]:
df_h = df[df["Industry"]=="Hollywood"]
df_b = df[df["Industry"]=="Bollywood"]

print("Hollywood movies statistics:",df_h.Rating.mean(),df_h.Rating.min(),df_h.Rating.max())
print("Bollywood movies statistics:",df_b.Rating.mean(),df_b.Rating.min(),df_b.Rating.max())

Hollywood movies statistics: 7.126666666666667 3.4 9.5
Bollywood movies statistics: 6.383333333333334 3.2 9.9